INSERT INTO users(name, age) VALUES("Eelan", 33);
INSERT INTO users(name, age) VALUES("Amy", 30);
INSERT INTO users(name, age) VALUES("Adam", 25);
INSERT INTO users(name, age) VALUES("John", 35);
INSERT INTO users(name, age) VALUES("Michelle", 23);
INSERT INTO users(name, age) VALUES("Mike", 39);
INSERT INTO users(name, age) VALUES("Roger", 40);
INSERT INTO users(name, age) VALUES("Grace", 24);
INSERT INTO users(name, age) VALUES("Maureen", 26);
INSERT INTO users(name, age) VALUES("Joe", 31);
INSERT INTO users(name, age) VALUES("Amanda", 29);
INSERT INTO users(name, age) VALUES("Paula", 42);
INSERT INTO users(name, age) VALUES("Eddie", 33);
INSERT INTO users(name, age) VALUES("Phil", 38);
INSERT INTO users(name, age) VALUES("Maddie", 21);
INSERT INTO users(name, age) VALUES("Addison", 24);
INSERT INTO users(name, age) VALUES("Yukiha", 39);
INSERT INTO users(name, age) VALUES("Helen", 32);
INSERT INTO users(name, age) VALUES("Mike", 29);
INSERT INTO users(name, age) VALUES("Karen", 30);

INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES("A", "1", 10000, "01.01.18", "12.31.18");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES("B", "2", 16000, "02.17.18", "04.28.19");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES("C", "3", 20500, "01.17.17", "07.30.20");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES("D", "4", 17000, "01.01.16", "09.30.19");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES("E", "5", 5000, "04.17.15", "01.20.22");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES("F", "6", 8000, "06.15.18", "10.30.18");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES("G", "7", 10000, "10.17.17", "12.17.19");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES("H", "8", 2000, "01.01.10", "01.01.17");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES("I", "9", 18000, "02.04.17", "03.10.19");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES("J", "10", 1500, "11.15.18", "07.27.22");

INSERT INTO pledges(amount, user_id, project_id) VALUES(20, 1, 1);
INSERT INTO pledges(amount, user_id, project_id) VALUES(100, 2, 2);
INSERT INTO pledges(amount, user_id, project_id) VALUES(8, 3, 3);
INSERT INTO pledges(amount, user_id, project_id) VALUES(10, 4, 4);
INSERT INTO pledges(amount, user_id, project_id) VALUES(10, 5, 5);
INSERT INTO pledges(amount, user_id, project_id) VALUES(6, 6, 6);
INSERT INTO pledges(amount, user_id, project_id) VALUES(9, 7, 7);
INSERT INTO pledges(amount, user_id, project_id) VALUES(8, 8, 8);
INSERT INTO pledges(amount, user_id, project_id) VALUES(9, 9, 9);
INSERT INTO pledges(amount, user_id, project_id) VALUES(10, 10, 10);
INSERT INTO pledges(amount, user_id, project_id) VALUES(11, 11, 1);
INSERT INTO pledges(amount, user_id, project_id) VALUES(12, 12, 2);
INSERT INTO pledges(amount, user_id, project_id) VALUES(13, 13, 3);
INSERT INTO pledges(amount, user_id, project_id) VALUES(14, 14, 4);
INSERT INTO pledges(amount, user_id, project_id) VALUES(15, 15, 5);
INSERT INTO pledges(amount, user_id, project_id) VALUES(16, 16, 6);
INSERT INTO pledges(amount, user_id, project_id) VALUES(17, 17, 7);
INSERT INTO pledges(amount, user_id, project_id) VALUES(18, 18, 8);
INSERT INTO pledges(amount, user_id, project_id) VALUES(19, 19, 9);
INSERT INTO pledges(amount, user_id, project_id) VALUES(10, 20, 10);
INSERT INTO pledges(amount, user_id, project_id) VALUES(1, 1, 1);
INSERT INTO pledges(amount, user_id, project_id) VALUES(6, 2, 2);
INSERT INTO pledges(amount, user_id, project_id) VALUES(10, 3, 3);
INSERT INTO pledges(amount, user_id, project_id) VALUES(17, 4, 4);
INSERT INTO pledges(amount, user_id, project_id) VALUES(5, 5, 5);
INSERT INTO pledges(amount, user_id, project_id) VALUES(4, 6, 6);
INSERT INTO pledges(amount, user_id, project_id) VALUES(9, 7, 7);
INSERT INTO pledges(amount, user_id, project_id) VALUES(5, 8, 8);
INSERT INTO pledges(amount, user_id, project_id) VALUES(5, 9, 9);
INSERT INTO pledges(amount, user_id, project_id) VALUES(5, 10, 10);
