INSERT INTO projects (title, category, start_date, end_date) VALUES ("Project", "Miscellenous", "March 1st", "December 3rd");
INSERT INTO projects (title, category, start_date, end_date) VALUES ("Project2", "Miscellenous", "March 1st", "December 3rd");
INSERT INTO projects (title, category, start_date, end_date) VALUES ("Project3", "Miscellenous", "March 1st", "December 3rd");
INSERT INTO projects (title, category, start_date, end_date) VALUES ("Project4", "Miscellenous", "March 1st", "December 3rd");
INSERT INTO projects (title, category, start_date, end_date) VALUES ("Project5", "Miscellenous", "March 1st", "December 3rd");
INSERT INTO projects (title, category, start_date, end_date) VALUES ("Project6", "Miscellenous", "March 1st", "December 3rd");
INSERT INTO projects (title, category, start_date, end_date) VALUES ("Project7", "Miscellenous", "March 1st", "December 3rd");
INSERT INTO projects (title, category, start_date, end_date) VALUES ("Project8", "Miscellenous", "March 1st", "December 3rd");
INSERT INTO projects (title, category, start_date, end_date) VALUES ("Project9", "Miscellenous", "March 1st", "December 3rd");
INSERT INTO projects (title, category, start_date, end_date) VALUES ("Project10", "Miscellenous", "March 1st", "December 3rd");

INSERT INTO users (name, age) VALUES ("Name1", 3);
INSERT INTO users (name, age) VALUES ("Name2", 6);
INSERT INTO users (name, age) VALUES ("Name3", 3);
INSERT INTO users (name, age) VALUES ("Name4", 3);
INSERT INTO users (name, age) VALUES ("Name5", 3);
INSERT INTO users (name, age) VALUES ("Name6", 3);
INSERT INTO users (name, age) VALUES ("Name7", 3);
INSERT INTO users (name, age) VALUES ("Name8", 7);
INSERT INTO users (name, age) VALUES ("Name9", 3);
INSERT INTO users (name, age) VALUES ("Name10", 3);
INSERT INTO users (name, age) VALUES ("Name11", 3);
INSERT INTO users (name, age) VALUES ("Name12", 3);
INSERT INTO users (name, age) VALUES ("Name13", 3);
INSERT INTO users (name, age) VALUES ("Name14", 3);
INSERT INTO users (name, age) VALUES ("Name15", 3);
INSERT INTO users (name, age) VALUES ("Name16", 3);
INSERT INTO users (name, age) VALUES ("Name17", 3);
INSERT INTO users (name, age) VALUES ("Name18", 3);
INSERT INTO users (name, age) VALUES ("Name19", 3);
INSERT INTO users (name, age) VALUES ("Name20", 3);

INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 7);
