INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("A", "space", 9000000, "01-01-20", "04-28-18");;
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("B", "ending world hunger", 10000000, "01-01-22", "04-28-18");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("C", "fixing the national debt", 1000000000000, "01-01-32", "04-28-18");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("D", "fixing my squat form", 100, "05-28-18", "04-28-18");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("E", "getting a sixpack", 200, "06-27-18", "04-28-18");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("F", "deep sea exploration", 65000000, "01-01-21", "04-28-18");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("G", "extra terestrial life search", 350000000, "01-01-55", "04-28-18");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("H", "telekenesis", 5000000, "02-01-30", "04-28-18");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("I", "VR", 2000000, "01-01-22", "04-28-18");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("J", "psychadelic enlightenment", 1, "04-28-19", "04-28-18");

INSERT INTO users (name, age) VALUES ("Ryan", 24);
INSERT INTO users (name, age) VALUES ("Joe", 25);
INSERT INTO users (name, age) VALUES ("Ryan E", 24);
INSERT INTO users (name, age) VALUES ("Duncan", 25);
INSERT INTO users (name, age) VALUES ("Melissa", 27);
INSERT INTO users (name, age) VALUES ("Ghinwah", 21);
INSERT INTO users (name, age) VALUES ("Lola", 24);
INSERT INTO users (name, age) VALUES ("Rebecca", 22);
INSERT INTO users (name, age) VALUES ("Iona", 10);
INSERT INTO users (name, age) VALUES ("Jonn", 10);
INSERT INTO users (name, age) VALUES ("Kellyn", 11);
INSERT INTO users (name, age) VALUES ("Loreon", 11);
INSERT INTO users (name, age) VALUES ("Mathin", 11);
INSERT INTO users (name, age) VALUES ("Naerys", 11);
INSERT INTO users (name, age) VALUES ("Obany", 11);
INSERT INTO users (name, age) VALUES ("Pennei", 11);
INSERT INTO users (name, age) VALUES ("Quinlan", 11);
INSERT INTO users (name, age) VALUES ("Rosalind", 11);
INSERT INTO users (name, age) VALUES ("Sarmion", 11);
INSERT INTO users (name, age) VALUES ("Tanyth", 11);

INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 3, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 4, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 5, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 6, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 8, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 10, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 11, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 12, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 13, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 14, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 15, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 16, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 17, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 18, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 19, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 20, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 3, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 4, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 5, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 6, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 8, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 10, 10)
